[package]
name = "jito-protos"
description = "Jito relayer protobuf code"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = { workspace = true }
bincode = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
solana-perf = { workspace = true }
solana-sdk = { workspace = true }
tonic = { workspace = true }

[build-dependencies]
protobuf-src = { workspace = true }
tonic-build = { workspace = true }
